<h3 style="text-align:center">Mohsen Shiri-Ali Chalaki</h3>
<h5 style="text-align:center">Recognizing music style</h5>

<h5 style="text-align:center">Classification method: SVM</h5>

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn import preprocessing

In [3]:
df=pd.read_csv('./MusicDataSet.csv')
x=df[['Tempo', 'RMS max', 'RMS min', 'RMS mean', 'RMS median',
       'Spectrogram max', 'Spectrogram mean', 'mfccs max',
       'mfccs min', 'mfccs mean', 'chromagram min', 'chromagram mean',
       'NumberStrongNote0.5&0.7', 'NumberWeakNote0.2&0.3', 'Boss Power',
       'Mean TimePattern']].values
y=df["Label"].values

In [7]:
scaler=preprocessing.Normalizer().fit(x)
X=scaler.transform(x.astype(float))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
svm_model = SVC(kernel='linear')

# آموزش مدل
svm_model.fit(X_train, y_train)

# پیش‌بینی برچسب‌ها برای داده‌های تست
y_pred = svm_model.predict(X_test)

# نمایش نتایج
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[ 0 21  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0]
 [ 0 24  0  0  0  0  0  0  0  0]
 [ 0 22  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0]
 [ 0 27  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0]
 [ 0 22  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]]

Classification Report:
              precision    recall  f1-score   support

       blues       0.00      0.00      0.00        21
   classical       0.06      1.00      0.11        12
     country       0.00      0.00      0.00        24
       disco       0.00      0.00      0.00        22
      hiphop       0.00      0.00      0.00        15
        jazz       0.00      0.00      0.00        27
       metal       0.00      0.00      0.00        18
         pop       0.00      0.00      0.00        19
      reggae       0.00      0.00      0.00        22
        rock       0.00      0.00      0.00        20

    accuracy                   

c:\Users\LEGION5 PRO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\LEGION5 PRO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\LEGION5 PRO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  